alter table public.pedido
  add column if not exists cancelado_em timestamptz,
  add column if not exists motivo_cancelamento text,
  add column if not exists cancelado_por text;

create table if not exists public.pedido_evento (
  id bigint generated by default as identity primary key,
  pedido_id bigint not null,
  tipo text not null,
  status_anterior text,
  status_novo text,
  motivo text,
  dados jsonb,
  created_at timestamptz not null default now()
);

create index if not exists pedido_evento_pedido_id_idx
  on public.pedido_evento (pedido_id, created_at desc);
