create table if not exists public.cj_sync_log (
  id bigint generated by default as identity primary key,
  pedido_id bigint not null,
  cj_order_id text not null,
  status_anterior text,
  status_novo text,
  tracking_code text,
  erro text,
  created_at timestamptz not null default now()
);
