create table if not exists public.pedido_notificacao (
  id bigint generated by default as identity primary key,
  pedido_id bigint not null,
  tipo text not null,
  created_at timestamptz not null default now(),
  constraint pedido_notificacao_tipo_check
    check (tipo in ('TRACKING_AVAILABLE', 'ORDER_DELIVERED')),
  constraint pedido_notificacao_pedido_tipo_unique
    unique (pedido_id, tipo)
);
