DO $$
DECLARE
	pedido_id_type text;
BEGIN
	SELECT format_type(att.atttypid, att.atttypmod)
	INTO pedido_id_type
	FROM pg_attribute att
	WHERE att.attrelid = 'public.pedido'::regclass
		AND att.attname = 'id'
		AND NOT att.attisdropped;

	IF pedido_id_type IS NULL THEN
		RAISE EXCEPTION 'public.pedido(id) was not found';
	END IF;

	EXECUTE format(
		'CREATE TABLE IF NOT EXISTS public.pedido_evento (
			id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			pedido_id %s NOT NULL,
			tipo text NOT NULL,
			status_anterior text,
			status_novo text,
			motivo text,
			dados jsonb,
			created_at timestamptz NOT NULL DEFAULT now()
		)',
		pedido_id_type
	);

	IF EXISTS (
		SELECT 1
		FROM pg_constraint con
		JOIN pg_attribute att
			ON att.attrelid = con.conrelid
			AND att.attname = 'id'
			AND NOT att.attisdropped
		WHERE con.conrelid = 'public.pedido'::regclass
			AND con.contype IN ('p', 'u')
			AND con.conkey = ARRAY[att.attnum]::smallint[]
	) AND NOT EXISTS (
		SELECT 1
		FROM pg_constraint
		WHERE conrelid = 'public.pedido_evento'::regclass
			AND conname = 'pedido_evento_pedido_id_fkey'
	) THEN
		ALTER TABLE public.pedido_evento
			ADD CONSTRAINT pedido_evento_pedido_id_fkey
			FOREIGN KEY (pedido_id) REFERENCES public.pedido(id);
	END IF;
END;
$$;

ALTER TABLE public.pedido_evento ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.pedido_evento FROM anon, authenticated;
GRANT INSERT ON TABLE public.pedido_evento TO service_role;
GRANT SELECT ON TABLE public.pedido_evento TO service_role;

NOTIFY pgrst, 'reload schema';
